#!/bin/sh
wget -P "ACC" https://tcga.xenahubs.net/download/TCGA.ACC.sampleMap/mutation_curated_broad_gene
wget -P "CESC" https://tcga.xenahubs.net/download/TCGA.CESC.sampleMap/mutation_ucsc_maf_gene
wget -P "CHOL" https://tcga.xenahubs.net/download/TCGA.CHOL.sampleMap/mutation_broad_gene
wget -P "DLBC" https://tcga.xenahubs.net/download/TCGA.DLBC.sampleMap/mutation_bcm_gene
wget -P "ESCA" https://tcga.xenahubs.net/download/TCGA.ESCA.sampleMap/mutation_broad_gene
wget -P "KICH" https://tcga.xenahubs.net/download/TCGA.KICH.sampleMap/mutation_broad_gene
wget -P "KIRC" https://tcga.xenahubs.net/download/TCGA.KIRC.sampleMap/mutation
wget -P "KIRP" https://tcga.xenahubs.net/download/TCGA.KIRP.sampleMap/mutation_curated_broad_gene
wget -P "LIHC" https://tcga.xenahubs.net/download/TCGA.LIHC.sampleMap/mutation_bcm_gene
wget -P "MESO" https://tcga.xenahubs.net/download/TCGA.MESO.sampleMap/mutation_broad_gene
wget -P "OV" https://tcga.xenahubs.net/download/TCGA.OV.sampleMap/mutation
wget -P "PCPG" https://tcga.xenahubs.net/download/TCGA.PCPG.sampleMap/mutation_broad_gene
wget -P "SARC" https://tcga.xenahubs.net/download/TCGA.SARC.sampleMap/mutation_broad_gene
wget -P "SKCM" https://tcga.xenahubs.net/download/TCGA.SKCM.sampleMap/mutation_broad_gene
wget -P "STAD" https://tcga.xenahubs.net/download/TCGA.STAD.sampleMap/mutation_curated_broad_gene
wget -P "TGCT" https://tcga.xenahubs.net/download/TCGA.TGCT.sampleMap/mutation_broad_gene
wget -P "THCA" https://tcga.xenahubs.net/download/TCGA.THCA.sampleMap/mutation_broad_gene
wget -P "THYM" https://tcga.xenahubs.net/download/TCGA.THYM.sampleMap/mutation_broad_gene
wget -P "UCEC" https://tcga.xenahubs.net/download/TCGA.UCEC.sampleMap/mutation
wget -P "UCS" https://tcga.xenahubs.net/download/TCGA.UCS.sampleMap/mutation_broad_gene
wget -P "UVM" https://tcga.xenahubs.net/download/TCGA.UVM.sampleMap/mutation_curated_broad_gene